name: Create release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release-create:
    runs-on: ubuntu-22.04
    steps:
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ github.ref }}
        tag_name: ${{ github.ref }}
        body_path: history.rst
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
