name: Create release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release-create:
    permissions: write-all
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Convert rst to markdown
      uses: docker://pandoc/core:3.5
      with:
        args: -f rst -t markdown -o HISTORY.md HISTORY.rst
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ github.ref }}
        tag_name: ${{ github.ref }}
        body_path: HISTORY.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
